project:
  type: website
  output-dir: docs
  
website:
  title: "nathan alexander, phd"
  navbar:
    left:
      - href: about
        text: about
      - href: "https://profiles.howard.edu/nathan-alexander"
        text: work
        
    tools:
      - icon: twitter
        href: https://twitter.com/professornaite
      - icon: github
        href: https://github.com/professornaite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; copyright 2026, nathan alexander"

format:
  html:
    theme: default
    css: 
      - styles/site.css
    toc: false

editor: source

