project:
  type: website
  output-dir: docs
  
website:
  title: "Nathan Alexander, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: me.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    tools:
      - icon: twitter
        href: https://twitter.com/professornaite
      - icon: github
        href: https://github.com/professornaite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Nathan Alexander"

format:
  html:
    theme: default
    toc: true

editor: source

